# Generated by Django 5.1.4 on 2025-01-03 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_alter_category_options_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='income',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
