# Generated by Django 5.1.4 on 2025-01-03 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_remove_expense_category_remove_income_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['user'], name='finances_ex_user_id_cf7c32_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='finances_ex_date_81e0d1_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['user'], name='finances_in_user_id_da5809_idx'),
        ),
        migrations.AddIndex(
            model_name='income',
            index=models.Index(fields=['date'], name='finances_in_date_bf3818_idx'),
        ),
    ]
