# Generated by Django 5.1.4 on 2025-01-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_expense_finances_ex_user_id_cf7c32_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name': 'Income', 'verbose_name_plural': 'Incomes'},
        ),
    ]
