# Generated by Django 4.2.17 on 2025-03-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_billupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
