# Generated by Django 4.2.17 on 2025-03-19 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0007_expense_category_income_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis_type', models.CharField(max_length=50)),
                ('analysis_period', models.CharField(blank=True, max_length=50, null=True)),
                ('insights', models.TextField()),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Financial Analysis',
                'verbose_name_plural': 'Financial Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
