# Generated by Django 5.1.4 on 2026-01-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_financialanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='For monthly recurring only (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='frequency',
            field=models.CharField(blank=True, choices=[('', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='income',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, help_text='For monthly recurring only (1-31)', null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='frequency',
            field=models.CharField(blank=True, choices=[('', 'One-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='income',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
    ]
